CREATE DATABASE [Service] 
GO
USE [Service]

CREATE TABLE Users
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Username VARCHAR(30) UNIQUE NOT NULL,
Password VARCHAR(50) NOT NULL,
Name VARCHAR(50) NULL,
Birthdate DATETIME2 NULL,
Age INT CHECK(Age BETWEEN 14 AND 110),
Email VARCHAR(50) NOT NULL
)

CREATE TABLE Departments
(
Id INT PRIMARY KEY NOT NULL IDENTITY,
Name VARCHAR(50) NOT NULL
)

CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName VARCHAR(25) NULL,
	LastName VARCHAR(25) NULL,
	Birthdate DATETIME NULL,
	Age INT CHECK(Age between 18 and 110),
	DepartmentId INT REFERENCES Departments(Id)
)

CREATE TABLE Categories
(
Id INT PRIMARY KEY NOT NULL IDENTITY,
Name VARCHAR(50) NOT NULL,
DepartmentId INT REFERENCES Departments(Id) NOT NULL
)

CREATE TABLE [Status]
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Label] VARCHAR(30) NOT NULL
)

CREATE TABLE Reports
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
CategoryId INT REFERENCES Categories(Id) NOT NULL,
StatusId INT REFERENCES Status(Id) NOT NULL,
OpenDate DATETIME NOT NULL,
CloseDate DATETIME NULL,
[Description] VARCHAR(200) NOT NULL,
UserId INT REFERENCES Users(Id) NOT NULL,
EmployeeId INT REFERENCES Employees(Id)
)


